[package]
name = "jet-doctor"
version = "0.2.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
publish = false

[workspace]
members = ["."]

[dependencies]
anyhow = "1.0"
onlyargs = "0.1"
onlyargs_derive = "0.1"
pem = "3.0"
shadow-rs = "0.21"
openssl-probe = "0.1"

# Same dependency as tokio-tungstenite 0.21.0
# https://crates.io/crates/tokio-tungstenite/0.21.0/dependencies
rustls = "0.22"
rustls-native-certs = "0.7"

[build-dependencies]
shadow-rs = "0.21"
