using System.Text.Json;
using System.Text.Json.Serialization;

namespace Devolutions.Gateway.Utils;

public interface IGatewayClaims
{
    string GetContentType();

    /// <summary>Default lifetime in seconds for this claims</summary>
    ///
    /// <remarks>When returning null, a token valid forever is generated by default.</remarks>
    long? GetDefaultLifetime()
    {
        return 300;
    }
}