#!/bin/sh

# System-wide package configuration.
DEFAULTS_FILE="/etc/default/devolutions-gateway"

if [ ! -d /etc/devolutions-gateway ]; then
	/bin/mkdir /etc/devolutions-gateway
	/bin/chmod 655 /etc/devolutions-gateway
fi
