#!/bin/sh

set -e

action="$1"

# Only do complete clean-up on purge.
if [ "$action" != "purge" ] ; then
  exit 0
fi

# System-wide package configuration.
DEFAULTS_FILE="/etc/default/devolutions-gateway"

if [ -s "$DEFAULTS_FILE" ]; then
  rm "$DEFAULTS_FILE" || exit 1
fi
