import { Injectable } from '@angular/core';
import { AdTranslator } from '@devolutions/web-active-directory-gui';

@Injectable()
export class ActiveDirectoryTranslatorService implements AdTranslator {
  private readonly translations: Record<string, string> = {
    btnCancel: 'Cancel',
    btnClose: 'Close',
    btnCreate: 'Create',
    btnDelete: 'Delete',
    btnEdit: 'Edit',
    btnNo: 'No',
    btnOk: 'OK',
    btnSave: 'Save',
    btnYes: 'Yes',
    ActiveDirectoryGroupScope_DomainLocal: 'Domain local',
    ActiveDirectoryGroupScope_Global: 'Global',
    ActiveDirectoryGroupScope_Universal: 'Universal',
    ActiveDirectoryGroupType_Distribution: 'Distribution',
    ActiveDirectoryGroupType_Security: 'Security',
    AlreadyExists: 'Already exists',
    AnErrorOccurredWhileSearchingForX: 'An error occurred while searching for {0}',
    AnUnexpectedErrorOccured: 'An unexpected error occurred',
    BitLockerMessageFormat:
      'Recovery Password:\r\n      {0}\r\n      {1}\r\n\r\nComputer: {2}\r\nDate: {3}\r\nPassword ID: {4}',
    ConnectionLogMessage_ResetPassword: 'Reset password',
    ConnectionLogMessage_UserResetPassword: 'User reset password',
    CopiedToClipboard: 'Copied to clipboard',
    DoYouReallyWantToDeleteX: 'Do you really want to delete {0}?',
    DoYouReallyWantToDisableTheSelectedUser: 'Do you really want to disable the selected user?',
    DoYouReallyWantToEnableTheSelectedUser: 'Do you really want to enable the selected user?',
    DoYouWantToUnlockTheUserX: 'Do you want to unlock the user {0}?',
    FailedToGetChildGroupsOfActiveDirectoryGroupX: 'Failed to get child groups of Active Directory group {0}',
    MissingRequiredSettings: 'Missing required settings',
    OperationFailed: 'Operation failed',
    TheGroupHasBeenSuccessfullyCreated: 'The group has been successfully created',
    TheObjectHasBeenSuccessfullyDeleted: 'The object has been successfully deleted',
    ThePasswordHasBeenSuccessfullyReset: 'The password has been successfully reset',
    TheUserHasBeenSuccessfullyCreated: 'The user has been successfully created',
    TheUserHasBeenSuccessfullyDisabled: 'The user has been successfully disabled.',
    TheUserHasBeenSuccessfullyEnabled: 'The user has been successfully enabled',
    TheUserHasBeenSuccessfullyUnlocked: 'The user has been successfully unlocked',
    UnableToCopy: 'Unable to Copy',
    lblNo: 'No',
    lblYes: 'Yes',
    YourConnectionIsNotReady: 'Your connection is not ready',
    YouMustFillAllFieldsBeforeContinuing: 'You must fill in all fields before continuing.',
    OperationNotPermitted: 'Operation not permitted',
    OperationsError: 'Operations error',
    error: 'Error',
    errBindFailed: 'Authentication failed',
    errConnectionFailed: 'Failed to connect to Active Directory',
    errInvalidCredentials: 'Invalid credentials',
    errOperationFailed: 'Operation failed',
    errPermissionDenied: 'Permission denied',
    errSearchFailed: 'Search failed',
    errTimeout: 'Operation timed out',
    ldapAlreadyExists: 'Object already exists',
    ldapAuthMethodNotSupported: 'Authentication method not supported',
    ldapBusy: 'Server is busy',
    ldapConstraintViolation: 'Constraint violation',
    ldapInsufficientAccessRights: 'Insufficient access rights',
    ldapInvalidCredentials: 'Invalid credentials',
    ldapInvalidDNSyntax: 'Invalid DN syntax',
    ldapNoSuchObject: 'Object not found',
    ldapOperationsError: 'Operations error',
    ldapProtocolError: 'Protocol error',
    ldapSizeLimitExceeded: 'Size limit exceeded',
    ldapStrongAuthRequired: 'Strong authentication required',
    ldapSuccess: 'Operation completed successfully',
    ldapTimeLimitExceeded: 'Time limit exceeded',
    ldapUnavailable: 'Server is unavailable',
    ldapUnwillingToPerform: 'Server unwilling to perform',
    ldapdisplayname: 'Display Name',
    lblAccountName: 'Account Name',
    lblActiveDirectoryBitLockerFind: 'Find BitLocker Recovery Password',
    lblActiveDirectoryPropertyListEditor: 'Property List Editor',
    lblActiveDirectoryPropertyValueEditor: 'Property Value Editor',
    lblActiveDirectoryUserProperties: 'User Properties',
    lblAdd: 'Add',
    lblAddMembers: 'Add Members',
    lblAllPrinters: 'All Printers',
    lblAttribute: 'Attribute',
    lblAttributes: 'Attributes',
    lblBitLocker: 'BitLocker',
    lblBitLockerRecoveryPassword: 'BitLocker Recovery Password',
    lblCancel: 'Cancel',
    lblClear: 'Clear',
    lblCloseSession: 'Close Session',
    lblCommonName: 'Name',
    lblComputer: 'Computer',
    lblConfirm: 'Confirm',
    lblConnect: 'Connect',
    lblContainer: 'Container',
    lblCopyToClipboard: 'Copy to Clipboard',
    lblCreationDate: 'Creation Date',
    lblDelete: 'Delete',
    lblDisable: 'Disable',
    lblDisabled: 'Disabled',
    lblDisconnect: 'Disconnect',
    lblDistinguishedName: 'Distinguished Name',
    lblDomain: 'Domain',
    lblEdit: 'Edit',
    lblEnable: 'Enable',
    lblEnterTextToSearch: 'Enter text to search',
    lblExpand: 'Expand',
    lblFilter: 'Filter',
    lblFullName: 'Full Name',
    lblGroup: 'Group',
    lblGroupName: 'Group Name',
    lblGroupPolicySettings: 'Group Policy Settings',
    lblGroupProperties: 'Group Properties',
    lblGroupScope: 'Group Scope',
    lblGroupType: 'Group Type',
    lblHidePassword: 'Hide Password',
    lblLastModifiedOn: 'Last Modified',
    lblLoading: 'Loading...',
    lblMember: 'Member',
    lblMemberOf: 'Member Of',
    lblMembers: 'Members',
    lblMore: 'More',
    lblMustChangePasswordAtNextLogon: 'Must change password at next logon',
    lblName: 'Name',
    lblNewGroup: 'New Group',
    lblNewUser: 'New User',
    lblNoDataToDisplay: 'No data to display',
    lblNoResultsFound: 'No results found',
    lblOk: 'OK',
    lblOrganizationalUnit: 'Organizational Unit',
    lblPassword: 'Password',
    lblPasswordID: 'Password ID',
    lblProperties: 'Properties',
    lblRecentlyDisabled: 'Recently Disabled',
    lblRecentlyLocked: 'Recently Locked',
    lblRecentlyModified: 'Recently Modified',
    lblRefresh: 'Refresh',
    lblRemove: 'Remove',
    lblResults: 'Results',
    lblRevealPassword: 'Reveal Password',
    lblSamAccountName: 'SAM Account Name',
    lblSave: 'Save',
    lblSearch: 'Search',
    lblSelect: 'Select',
    lblType: 'Type',
    lblUnlock: 'Unlock',
    lblUPNLogonName: 'UPN Logon Name',
    lblUser: 'User',
    lblUserCreatedButPasswordFailed: 'User created, but password update failed',
    lblValue: 'Value',
    lblValues: 'Values',
    lblValueToAdd: 'Value to Add',
    lblWarning: 'Warning',
    msgConfirmDelete: 'Are you sure you want to delete this item?',
    msgConnected: 'Connected to Active Directory',
    msgConnectionLost: 'Connection to Active Directory lost',
    msgDeleteSuccess: 'Item deleted successfully',
    msgDisconnected: 'Disconnected from Active Directory',
    msgError: 'An error occurred',
    msgNoResults: 'No results found',
    msgSaveSuccess: 'Changes saved successfully',
    msgSessionTerminated: 'Session has been terminated',
    msgSuccess: 'Success',
  };

  translate(key: string, valuesToInclude?: Record<string, string | number> | Array<string | number>): string {
    const translatedKey = this.translations[key] ?? key;

    if (!valuesToInclude) {
      return translatedKey;
    }

    if (Array.isArray(valuesToInclude)) {
      return valuesToInclude.reduce<string>(
        (translated, value, index) => translated.replace(new RegExp(`\\{${index}\\}`, 'g'), String(value)),
        translatedKey,
      );
    }

    return Object.entries(valuesToInclude).reduce(
      (translated, [name, value]) =>
        translated
          .replace(new RegExp(`\\{${name}\\}`, 'g'), String(value))
          .replace(new RegExp(`{{\\s*${name}\\s*}}`, 'g'), String(value)),
      translatedKey,
    );
  }
}
