#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Shared library for Devolutions Gateway Linux packaging smoke tests.
# Sourced by smoke-test-deb.sh and smoke-test-rpm.sh.
#
# Expects the following constants to be defined in the sourcing script
# before any check function is called:
#   BINARY          Path to the gateway binary.
#   LIB_DIR         Directory containing native libraries.
#   LIB_PATH        Path to libxmf.so.
#   WEBAPP_DIR      Path to the webapp root directory.
#   CONFIG_DIR      Path to the config directory.
#   CONFIG_FILE     Path to gateway.json.
#   UNIT_FILE_PATHS Array of candidate systemd unit file paths (in priority order).
# ──────────────────────────────────────────────────────────────────────────────

# ── Test bookkeeping ──────────────────────────────────────────────────────────

TESTS_PASSED=0
TESTS_FAILED=0

pass() { echo "✅ PASS: $1"; TESTS_PASSED=$((TESTS_PASSED + 1)); }
fail() { echo "❌ FAIL: $1" >&2; TESTS_FAILED=$((TESTS_FAILED + 1)); }
info() { echo "ℹ️  $1"; }
warn() { echo "⚠️  WARN: $1"; }

# ── Summary ───────────────────────────────────────────────────────────────────

summary() {
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  Test Summary: $TESTS_PASSED passed, $TESTS_FAILED failed"
    echo "════════════════════════════════════════════════════════════════"
    if [ "$TESTS_FAILED" -gt 0 ]; then
        exit 1
    fi
}

# ── Check functions ───────────────────────────────────────────────────────────

check_binary_executable() {
    if [ -x "$BINARY" ]; then
        pass "Main binary exists and is executable: $BINARY"
    else
        fail "Main binary missing or not executable: $BINARY"
    fi
}

check_native_library() {
    if [ -f "$LIB_PATH" ] && file "$LIB_PATH" 2>/dev/null | grep -q 'ELF'; then
        pass "Native library exists and is a valid ELF: $LIB_PATH"
    else
        fail "Native library missing or not a valid ELF: $LIB_PATH"
    fi
}

check_webapp() {
    if [ -d "$WEBAPP_DIR" ]; then
        pass "Webapp directory exists: $WEBAPP_DIR"
    else
        fail "Webapp directory missing: $WEBAPP_DIR"
    fi
    for app in client player; do
        if find "$WEBAPP_DIR/$app" -name 'index.html' 2>/dev/null | grep -q .; then
            pass "Webapp $app contains index.html"
        else
            fail "Webapp $app missing index.html"
        fi
    done
}

check_config_dir() {
    if [ -d "$CONFIG_DIR" ]; then
        pass "Config directory exists: $CONFIG_DIR"
    else
        fail "Config directory missing: $CONFIG_DIR"
    fi
}

check_binary_help() {
    HELP_OUTPUT=$("$BINARY" --help 2>&1) && HELP_RC=$? || HELP_RC=$?
    if [ "$HELP_RC" -eq 0 ] || echo "$HELP_OUTPUT" | grep -qi 'gateway\|usage\|help'; then
        pass "Binary responds to --help"
    else
        fail "Binary does not respond to --help (exit code: $HELP_RC)"
    fi
}

check_config_init() {
    if [ ! -f "$CONFIG_FILE" ]; then
        info "Config file not generated by postinst (expected without systemd)."
        info "Running config initialization manually…"
        CONFIG_INIT_LOG=$(mktemp)
        if "$BINARY" --config-init-only > "$CONFIG_INIT_LOG" 2>&1; then
            pass "Config initialization command succeeded"
        else
            echo "config-init-only output:"
            cat "$CONFIG_INIT_LOG"
            fail "Config initialization command failed"
        fi
        rm -f "$CONFIG_INIT_LOG"
    fi

    if [ -f "$CONFIG_FILE" ]; then
        pass "Default config file exists: $CONFIG_FILE"
        if python3 -c "import json; json.load(open('$CONFIG_FILE'))" 2>/dev/null; then
            pass "$(basename "$CONFIG_FILE") is valid JSON"
        else
            fail "$(basename "$CONFIG_FILE") exists but is not valid JSON"
        fi
    else
        fail "Default config file missing after initialization: $CONFIG_FILE"
    fi
}

# Usage: check_unit_file <fail|warn>
# Searches UNIT_FILE_PATHS in order; on absence, either fails or warns.
check_unit_file() {
    local on_absent="$1"
    local unit_file=""
    for path in "${UNIT_FILE_PATHS[@]}"; do
        if [ -f "$path" ]; then
            unit_file="$path"
            break
        fi
    done

    if [ -n "$unit_file" ]; then
        pass "systemd unit file exists: $unit_file"
        if grep -q "$BINARY" "$unit_file"; then
            pass "Unit file references correct binary path"
        else
            fail "Unit file does not reference $BINARY"
        fi
    elif [ "$on_absent" = "fail" ]; then
        fail "systemd unit file not found"
    else
        warn "systemd unit file not found after registration attempt."
        info "This is expected in container environments without systemd."
    fi
}

check_service_startup() {
    info "[Best-effort] Checking service startup…"
    warn "systemd service startup testing is best-effort in containers."
    warn "Full service validation requires a real systemd environment."
    if [ -d /run/systemd/system ]; then
        info "systemd detected; attempting service start…"
        if systemctl start devolutions-gateway 2>&1; then
            pass "[Best-effort] Service started successfully"
            systemctl status devolutions-gateway 2>&1 || true
        else
            warn "Service start failed (expected in some container environments)."
        fi
    else
        info "No systemd detected; skipping service startup test."
    fi
}
