#!/bin/sh

if [ ! -d /etc/devolutions-gateway ]; then
	/bin/mkdir /etc/devolutions-gateway
	/bin/chmod 655 /etc/devolutions-gateway
fi

if [ -d /run/systemd/system ]; then
	/usr/bin/devolutions-gateway service register >/dev/null
	systemctl daemon-reload
	/usr/bin/devolutions-gateway --config-init-only >/dev/null
	systemctl enable --now devolutions-gateway >/dev/null 2>&1
	systemctl restart devolutions-gateway >/dev/null 2>&1
fi
