[package]
name = "tracing-cov-mark"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
tracing = "0.1"
