#!/bin/sh

if [ ! -d /etc/devolutions-agent ]; then
	/bin/mkdir /etc/devolutions-agent
	/bin/chmod 655 /etc/devolutions-agent
fi

if [ -d /run/systemd/system ]; then
	/usr/bin/devolutions-agent service config init >/dev/null
fi

set -e
# Automatically added by dh_installsystemd/13.18ubuntu2.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.18ubuntu2.1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rp.service' >/dev/null || true
	fi
fi
# End automatically added section