#!/bin/sh

if [ ! -d /etc/devolutions-agent ]; then
	/bin/mkdir /etc/devolutions-agent
	/bin/chmod 655 /etc/devolutions-agent
fi

if [ -d /run/systemd/system ]; then
	/usr/bin/devolutions-agent config init >/dev/null
fi