#!/bin/sh

set -e

action="$1"
if [ "$2" = "in-favour" ]; then
  # Treat conflict remove as an upgrade.
  action="upgrade"
fi

# Don't clean-up just for an upgrade.`
if [ "$action" = "upgrade" ] ; then
  exit 0
fi

if [ -d /run/systemd/system ]; then
  systemctl stop devolutions-agent >/dev/null 2>&1
  /usr/bin/devolutions-agent service unregister >/dev/null
fi
