[package]
name = "network-monitor"
version = "0.0.0"
edition = "2024"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
publish = false

[dependencies]
network-scanner = { path = "../network-scanner" }
network-scanner-net = { path = "../network-scanner-net" }
serde = { version = "1", features = ["derive"] }
camino = { version = "1", features = ["serde1"] }
serde_json = "1"
thiserror = "1"
time = { version = "0.3", features = ["serde"] }
tokio = { version = "1.45", features= ["macros", "sync"] }
tokio-util = { version = "0.7" }
anyhow = "1"
tracing = "0.1"

[dev-dependencies]
tempdir = "0.3"
tokio-test = "0.4"

[lints]
workspace = true
