[package]
name = "network-monitor"
version = "0.0.0"
edition = "2024"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
publish = false

[dependencies]
anyhow = "1"
network-scanner-net = { path = "../network-scanner-net" }
network-scanner = { path = "../network-scanner" }
thiserror = "1"
time = { version = "0.3", features = ["serde"] }
tokio-util = { version = "0.7" }
tokio = { version = "1.45", features = ["macros", "sync"] }
tracing = "0.1"

[lints]
workspace = true
