/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticodeSignatureStatus {
    #[serde(rename = "Valid")]
    Valid,
    #[serde(rename = "Incompatible")]
    Incompatible,
    #[serde(rename = "NotSigned")]
    NotSigned,
    #[serde(rename = "HashMismatch")]
    HashMismatch,
    #[serde(rename = "NotSupportedFileFormat")]
    NotSupportedFileFormat,
    #[serde(rename = "NotTrusted")]
    NotTrusted,

}

impl ToString for AuthenticodeSignatureStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Valid => String::from("Valid"),
            Self::Incompatible => String::from("Incompatible"),
            Self::NotSigned => String::from("NotSigned"),
            Self::HashMismatch => String::from("HashMismatch"),
            Self::NotSupportedFileFormat => String::from("NotSupportedFileFormat"),
            Self::NotTrusted => String::from("NotTrusted"),
        }
    }
}

impl Default for AuthenticodeSignatureStatus {
    fn default() -> AuthenticodeSignatureStatus {
        Self::Valid
    }
}

