/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Certificate {
    #[serde(rename = "Base64")]
    pub base64: String,
    #[serde(rename = "Eku")]
    pub eku: Vec<String>,
    #[serde(rename = "Issuer")]
    pub issuer: String,
    #[serde(rename = "SerialNumber")]
    pub serial_number: String,
    #[serde(rename = "Subject")]
    pub subject: String,
    #[serde(rename = "Thumbprint")]
    pub thumbprint: models::Hash,
}

impl Certificate {
    pub fn new(
        base64: String,
        eku: Vec<String>,
        issuer: String,
        serial_number: String,
        subject: String,
        thumbprint: models::Hash,
    ) -> Certificate {
        Certificate {
            base64,
            eku,
            issuer,
            serial_number,
            subject,
            thumbprint,
        }
    }
}
