/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JitElevationLogRow {
    #[serde(rename = "Id")]
    pub id: i64,
    #[serde(rename = "Success")]
    pub success: i64,
    #[serde(rename = "TargetPath")]
    pub target_path: String,
    #[serde(rename = "Timestamp")]
    pub timestamp: i64,
    #[serde(rename = "User")]
    pub user: models::User,
}

impl JitElevationLogRow {
    pub fn new(id: i64, success: i64, target_path: String, timestamp: i64, user: models::User) -> JitElevationLogRow {
        JitElevationLogRow {
            id,
            success,
            target_path,
            timestamp,
            user,
        }
    }
}
