/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionElevationConfiguration {
    #[serde(rename = "Enabled")]
    pub enabled: bool,
}

impl SessionElevationConfiguration {
    pub fn new(enabled: bool) -> SessionElevationConfiguration {
        SessionElevationConfiguration {
            enabled,
        }
    }
}

