/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Signature {
    #[serde(rename = "Certificates", skip_serializing_if = "Option::is_none")]
    pub certificates: Option<Vec<models::Certificate>>,
    #[serde(rename = "Signer", skip_serializing_if = "Option::is_none")]
    pub signer: Option<models::Signer>,
    #[serde(rename = "Status")]
    pub status: models::AuthenticodeSignatureStatus,
}

impl Signature {
    pub fn new(status: models::AuthenticodeSignatureStatus) -> Signature {
        Signature {
            certificates: None,
            signer: None,
            status,
        }
    }
}
