/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StringFilter {
    #[serde(rename = "Data")]
    pub data: String,
    #[serde(rename = "Kind")]
    pub kind: models::StringFilterKind,
}

impl StringFilter {
    pub fn new(data: String, kind: models::StringFilterKind) -> StringFilter {
        StringFilter { data, kind }
    }
}
