/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemporaryElevationStatus {
    #[serde(rename = "Enabled")]
    pub enabled: bool,
    #[serde(rename = "MaximumSeconds")]
    pub maximum_seconds: u64,
    #[serde(rename = "TimeLeft")]
    pub time_left: u64,
}

impl TemporaryElevationStatus {
    pub fn new(enabled: bool, maximum_seconds: u64, time_left: u64) -> TemporaryElevationStatus {
        TemporaryElevationStatus {
            enabled,
            maximum_seconds,
            time_left,
        }
    }
}
