/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2025.3.2
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// Defines AddressFamily
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AddressFamily
    {
        /// <summary>
        /// Enum IPv4 for value: IPv4
        /// </summary>
        [EnumMember(Value = "IPv4")]
        IPv4 = 1,

        /// <summary>
        /// Enum IPv6 for value: IPv6
        /// </summary>
        [EnumMember(Value = "IPv6")]
        IPv6 = 2
    }

    public static class AddressFamilyExtensions
    {
        /// <summary>
        /// Returns the value as string for a given variant
        /// </summary>
        public static string ToValue(this AddressFamily variant)
        {
            switch (variant)
            {
                case AddressFamily.IPv4:
                    return "IPv4";
                case AddressFamily.IPv6:
                    return "IPv6";
                default:
                    throw new ArgumentOutOfRangeException(nameof(variant), $"Unexpected variant: {variant}");
            }
        }
    }

}
