/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2026.2.4
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// AgentInfo
    /// </summary>
    [DataContract(Name = "AgentInfo")]
    public partial class AgentInfo : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public AgentStatus Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AgentInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentInfo" /> class.
        /// </summary>
        /// <param name="agentId">Stable Agent identity. (required).</param>
        /// <param name="domains">Domain routes currently advertised by the Agent..</param>
        /// <param name="lastSeenMs">Last heartbeat timestamp in milliseconds since the Unix epoch..</param>
        /// <param name="name">Unique management name assigned during enrollment. (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="subnets">Subnet routes currently advertised by the Agent..</param>
        public AgentInfo(Guid agentId = default(Guid), List<AgentDomainAdvertisement> domains = default(List<AgentDomainAdvertisement>), long? lastSeenMs = default(long?), string name = default(string), AgentStatus status = default(AgentStatus), List<string> subnets = default(List<string>))
        {
            this.AgentId = agentId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for AgentInfo and cannot be null");
            }
            this.Name = name;
            this.Status = status;
            this.Domains = domains;
            this.LastSeenMs = lastSeenMs;
            this.Subnets = subnets;
        }

        /// <summary>
        /// Stable Agent identity.
        /// </summary>
        /// <value>Stable Agent identity.</value>
        [DataMember(Name = "agent_id", IsRequired = true, EmitDefaultValue = true)]
        public Guid AgentId { get; set; }

        /// <summary>
        /// Domain routes currently advertised by the Agent.
        /// </summary>
        /// <value>Domain routes currently advertised by the Agent.</value>
        [DataMember(Name = "domains", EmitDefaultValue = true)]
        public List<AgentDomainAdvertisement> Domains { get; set; }

        /// <summary>
        /// Last heartbeat timestamp in milliseconds since the Unix epoch.
        /// </summary>
        /// <value>Last heartbeat timestamp in milliseconds since the Unix epoch.</value>
        [DataMember(Name = "last_seen_ms", EmitDefaultValue = true)]
        public long? LastSeenMs { get; set; }

        /// <summary>
        /// Unique management name assigned during enrollment.
        /// </summary>
        /// <value>Unique management name assigned during enrollment.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Subnet routes currently advertised by the Agent.
        /// </summary>
        /// <value>Subnet routes currently advertised by the Agent.</value>
        [DataMember(Name = "subnets", EmitDefaultValue = true)]
        public List<string> Subnets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AgentInfo {\n");
            sb.Append("  AgentId: ").Append(AgentId).Append("\n");
            sb.Append("  Domains: ").Append(Domains).Append("\n");
            sb.Append("  LastSeenMs: ").Append(LastSeenMs).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Subnets: ").Append(Subnets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LastSeenMs (long?) minimum
            if (this.LastSeenMs < (long?)0)
            {
                yield return new ValidationResult("Invalid value for LastSeenMs, must be a value greater than or equal to 0.", new [] { "LastSeenMs" });
            }

            yield break;
        }
    }

}
