/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2026.2.4
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// Payload of a &#x60;succeeded&#x60; AI analysis Task: the log it added to the session
    /// </summary>
    [DataContract(Name = "AiAnalysisSucceededPayload")]
    public partial class AiAnalysisSucceededPayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiAnalysisSucceededPayload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AiAnalysisSucceededPayload() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AiAnalysisSucceededPayload" /> class.
        /// </summary>
        /// <param name="fileName">Name of the new log in the session manifest, such as &#x60;ai-analysis-0.slog&#x60;. (required).</param>
        /// <param name="model">Model that wrote the log, as reported by the AI provider; the requested model when it reports none. (required).</param>
        /// <param name="promptVersion">Version of the instructions sent to the AI provider. (required).</param>
        /// <param name="usage">usage.</param>
        public AiAnalysisSucceededPayload(string fileName = default(string), string model = default(string), string promptVersion = default(string), AiAnalysisUsage usage = default(AiAnalysisUsage))
        {
            // to ensure "fileName" is required (not null)
            if (fileName == null)
            {
                throw new ArgumentNullException("fileName is a required property for AiAnalysisSucceededPayload and cannot be null");
            }
            this.FileName = fileName;
            // to ensure "model" is required (not null)
            if (model == null)
            {
                throw new ArgumentNullException("model is a required property for AiAnalysisSucceededPayload and cannot be null");
            }
            this.Model = model;
            // to ensure "promptVersion" is required (not null)
            if (promptVersion == null)
            {
                throw new ArgumentNullException("promptVersion is a required property for AiAnalysisSucceededPayload and cannot be null");
            }
            this.PromptVersion = promptVersion;
            this.Usage = usage;
        }

        /// <summary>
        /// Name of the new log in the session manifest, such as &#x60;ai-analysis-0.slog&#x60;.
        /// </summary>
        /// <value>Name of the new log in the session manifest, such as &#x60;ai-analysis-0.slog&#x60;.</value>
        [DataMember(Name = "fileName", IsRequired = true, EmitDefaultValue = true)]
        public string FileName { get; set; }

        /// <summary>
        /// Model that wrote the log, as reported by the AI provider; the requested model when it reports none.
        /// </summary>
        /// <value>Model that wrote the log, as reported by the AI provider; the requested model when it reports none.</value>
        [DataMember(Name = "model", IsRequired = true, EmitDefaultValue = true)]
        public string Model { get; set; }

        /// <summary>
        /// Version of the instructions sent to the AI provider.
        /// </summary>
        /// <value>Version of the instructions sent to the AI provider.</value>
        [DataMember(Name = "promptVersion", IsRequired = true, EmitDefaultValue = true)]
        public string PromptVersion { get; set; }

        /// <summary>
        /// Gets or Sets Usage
        /// </summary>
        [DataMember(Name = "usage", EmitDefaultValue = true)]
        public AiAnalysisUsage Usage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiAnalysisSucceededPayload {\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  PromptVersion: ").Append(PromptVersion).Append("\n");
            sb.Append("  Usage: ").Append(Usage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
