/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2026.2.4
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// Payload of a &#x60;failed&#x60; AI analysis Task: why it failed
    /// </summary>
    [DataContract(Name = "AiAnalysisFailedPayload")]
    public partial class AiAnalysisFailedPayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiAnalysisFailedPayload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AiAnalysisFailedPayload() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AiAnalysisFailedPayload" /> class.
        /// </summary>
        /// <param name="attempts">Number of attempts started. (required).</param>
        /// <param name="details">What went wrong: a text, except for &#x60;timed out&#x60;, where it is &#x60;{ \&quot;lastPayload\&quot;: &lt;payload before the timeout&gt; }&#x60;. (required).</param>
        /// <param name="reason">Kind of failure, such as &#x60;permanent error&#x60;, &#x60;attempts exhausted&#x60;, &#x60;key lost&#x60; or &#x60;timed out&#x60;. (required).</param>
        public AiAnalysisFailedPayload(int attempts = default(int), Object details = default(Object), string reason = default(string))
        {
            this.Attempts = attempts;
            // to ensure "details" is required (not null)
            if (details == null)
            {
                throw new ArgumentNullException("details is a required property for AiAnalysisFailedPayload and cannot be null");
            }
            this.Details = details;
            // to ensure "reason" is required (not null)
            if (reason == null)
            {
                throw new ArgumentNullException("reason is a required property for AiAnalysisFailedPayload and cannot be null");
            }
            this.Reason = reason;
        }

        /// <summary>
        /// Number of attempts started.
        /// </summary>
        /// <value>Number of attempts started.</value>
        [DataMember(Name = "attempts", IsRequired = true, EmitDefaultValue = true)]
        public int Attempts { get; set; }

        /// <summary>
        /// What went wrong: a text, except for &#x60;timed out&#x60;, where it is &#x60;{ \&quot;lastPayload\&quot;: &lt;payload before the timeout&gt; }&#x60;.
        /// </summary>
        /// <value>What went wrong: a text, except for &#x60;timed out&#x60;, where it is &#x60;{ \&quot;lastPayload\&quot;: &lt;payload before the timeout&gt; }&#x60;.</value>
        [DataMember(Name = "details", IsRequired = true, EmitDefaultValue = true)]
        public Object Details { get; set; }

        /// <summary>
        /// Kind of failure, such as &#x60;permanent error&#x60;, &#x60;attempts exhausted&#x60;, &#x60;key lost&#x60; or &#x60;timed out&#x60;.
        /// </summary>
        /// <value>Kind of failure, such as &#x60;permanent error&#x60;, &#x60;attempts exhausted&#x60;, &#x60;key lost&#x60; or &#x60;timed out&#x60;.</value>
        [DataMember(Name = "reason", IsRequired = true, EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiAnalysisFailedPayload {\n");
            sb.Append("  Attempts: ").Append(Attempts).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Attempts (int) minimum
            if (this.Attempts < (int)0)
            {
                yield return new ValidationResult("Invalid value for Attempts, must be a value greater than or equal to 0.", new [] { "Attempts" });
            }

            yield break;
        }
    }

}
