/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2022.2.2
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// Defines DataEncoding
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DataEncoding
    {
        /// <summary>
        /// Enum Multibase for value: Multibase
        /// </summary>
        [EnumMember(Value = "Multibase")]
        Multibase = 1,

        /// <summary>
        /// Enum Base64 for value: Base64
        /// </summary>
        [EnumMember(Value = "Base64")]
        Base64 = 2,

        /// <summary>
        /// Enum Base64Pad for value: Base64Pad
        /// </summary>
        [EnumMember(Value = "Base64Pad")]
        Base64Pad = 3,

        /// <summary>
        /// Enum Base64Url for value: Base64Url
        /// </summary>
        [EnumMember(Value = "Base64Url")]
        Base64Url = 4,

        /// <summary>
        /// Enum Base64UrlPad for value: Base64UrlPad
        /// </summary>
        [EnumMember(Value = "Base64UrlPad")]
        Base64UrlPad = 5

    }

}
