/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2025.2.3
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// Defines PreflightOutputKind
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PreflightOutputKind
    {
        /// <summary>
        /// Enum Version for value: version
        /// </summary>
        [EnumMember(Value = "version")]
        Version = 1,

        /// <summary>
        /// Enum AgentVersion for value: agent-version
        /// </summary>
        [EnumMember(Value = "agent-version")]
        AgentVersion = 2,

        /// <summary>
        /// Enum RunningSessionCount for value: running-session-count
        /// </summary>
        [EnumMember(Value = "running-session-count")]
        RunningSessionCount = 3,

        /// <summary>
        /// Enum RecordingStorageHealth for value: recording-storage-health
        /// </summary>
        [EnumMember(Value = "recording-storage-health")]
        RecordingStorageHealth = 4,

        /// <summary>
        /// Enum ResolvedHost for value: resolved-host
        /// </summary>
        [EnumMember(Value = "resolved-host")]
        ResolvedHost = 5,

        /// <summary>
        /// Enum Alert for value: alert
        /// </summary>
        [EnumMember(Value = "alert")]
        Alert = 6
    }

    public static class PreflightOutputKindExtensions
    {
        /// <summary>
        /// Returns the value as string for a given variant
        /// </summary>
        public static string ToValue(this PreflightOutputKind variant)
        {
            switch (variant)
            {
                case PreflightOutputKind.Version:
                    return "version";
                case PreflightOutputKind.AgentVersion:
                    return "agent-version";
                case PreflightOutputKind.RunningSessionCount:
                    return "running-session-count";
                case PreflightOutputKind.RecordingStorageHealth:
                    return "recording-storage-health";
                case PreflightOutputKind.ResolvedHost:
                    return "resolved-host";
                case PreflightOutputKind.Alert:
                    return "alert";
                default:
                    throw new ArgumentOutOfRangeException(nameof(variant), $"Unexpected variant: {variant}");
            }
        }
    }

}
