/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2026.2.4
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// RecordingAiAnalysisSubstateOneOf
    /// </summary>
    [DataContract(Name = "RecordingAiAnalysisSubstate_oneOf")]
    public partial class RecordingAiAnalysisSubstateOneOf : IValidatableObject
    {
        /// <summary>
        /// Defines Step
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StepEnum
        {
            /// <summary>
            /// Enum Preparing for value: preparing
            /// </summary>
            [EnumMember(Value = "preparing")]
            Preparing = 1
        }


        /// <summary>
        /// Gets or Sets Step
        /// </summary>
        [DataMember(Name = "step", IsRequired = true, EmitDefaultValue = true)]
        public StepEnum Step { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordingAiAnalysisSubstateOneOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecordingAiAnalysisSubstateOneOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordingAiAnalysisSubstateOneOf" /> class.
        /// </summary>
        /// <param name="step">step (required).</param>
        public RecordingAiAnalysisSubstateOneOf(StepEnum step = default(StepEnum))
        {
            this.Step = step;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecordingAiAnalysisSubstateOneOf {\n");
            sb.Append("  Step: ").Append(Step).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
