/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2026.2.4
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// Session Recording Log search result
    /// </summary>
    [DataContract(Name = "RecordingLogSearchResponse")]
    public partial class RecordingLogSearchResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordingLogSearchResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecordingLogSearchResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordingLogSearchResponse" /> class.
        /// </summary>
        /// <param name="hits">Matching entries, ordered by recording, then by manifest file order, then by line (required).</param>
        /// <param name="limitReached">The hit limit or the response size bound was reached, so more matches may exist (required).</param>
        /// <param name="notFoundRecordingIds">Listed recordings that are not stored on this instance or have no readable manifest (required).</param>
        /// <param name="scanLimitReached">A scan bound was reached or an oversized line was skipped, so some entries were not searched (required).</param>
        public RecordingLogSearchResponse(List<RecordingLogSearchHit> hits = default(List<RecordingLogSearchHit>), bool limitReached = default(bool), List<Guid> notFoundRecordingIds = default(List<Guid>), bool scanLimitReached = default(bool))
        {
            // to ensure "hits" is required (not null)
            if (hits == null)
            {
                throw new ArgumentNullException("hits is a required property for RecordingLogSearchResponse and cannot be null");
            }
            this.Hits = hits;
            this.LimitReached = limitReached;
            // to ensure "notFoundRecordingIds" is required (not null)
            if (notFoundRecordingIds == null)
            {
                throw new ArgumentNullException("notFoundRecordingIds is a required property for RecordingLogSearchResponse and cannot be null");
            }
            this.NotFoundRecordingIds = notFoundRecordingIds;
            this.ScanLimitReached = scanLimitReached;
        }

        /// <summary>
        /// Matching entries, ordered by recording, then by manifest file order, then by line
        /// </summary>
        /// <value>Matching entries, ordered by recording, then by manifest file order, then by line</value>
        [DataMember(Name = "hits", IsRequired = true, EmitDefaultValue = true)]
        public List<RecordingLogSearchHit> Hits { get; set; }

        /// <summary>
        /// The hit limit or the response size bound was reached, so more matches may exist
        /// </summary>
        /// <value>The hit limit or the response size bound was reached, so more matches may exist</value>
        [DataMember(Name = "limitReached", IsRequired = true, EmitDefaultValue = true)]
        public bool LimitReached { get; set; }

        /// <summary>
        /// Listed recordings that are not stored on this instance or have no readable manifest
        /// </summary>
        /// <value>Listed recordings that are not stored on this instance or have no readable manifest</value>
        [DataMember(Name = "notFoundRecordingIds", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> NotFoundRecordingIds { get; set; }

        /// <summary>
        /// A scan bound was reached or an oversized line was skipped, so some entries were not searched
        /// </summary>
        /// <value>A scan bound was reached or an oversized line was skipped, so some entries were not searched</value>
        [DataMember(Name = "scanLimitReached", IsRequired = true, EmitDefaultValue = true)]
        public bool ScanLimitReached { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecordingLogSearchResponse {\n");
            sb.Append("  Hits: ").Append(Hits).Append("\n");
            sb.Append("  LimitReached: ").Append(LimitReached).Append("\n");
            sb.Append("  NotFoundRecordingIds: ").Append(NotFoundRecordingIds).Append("\n");
            sb.Append("  ScanLimitReached: ").Append(ScanLimitReached).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
