/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2026.2.4
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// Desired auto-update schedule to apply to Devolutions Agent.
    /// </summary>
    [DataContract(Name = "SetUpdateScheduleRequest")]
    public partial class SetUpdateScheduleRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetUpdateScheduleRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetUpdateScheduleRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetUpdateScheduleRequest" /> class.
        /// </summary>
        /// <param name="enabled">Enable periodic Devolutions Agent self-update checks. (required).</param>
        /// <param name="interval">Minimum interval between auto-update checks, in seconds.  &#x60;0&#x60; means check once at &#x60;UpdateWindowStart&#x60; (default)..</param>
        /// <param name="products">Products the agent autonomously polls for new versions (default: empty)..</param>
        /// <param name="updateWindowEnd">End of the maintenance window as seconds past midnight in local time, exclusive.  &#x60;null&#x60; (default) means no upper bound - a single check fires at &#x60;UpdateWindowStart&#x60;. When end &lt; start the window crosses midnight..</param>
        /// <param name="updateWindowStart">Start of the maintenance window as seconds past midnight in local time (default: &#x60;7200&#x60; &#x3D; 02:00)..</param>
        public SetUpdateScheduleRequest(bool enabled = default(bool), long interval = default(long), List<string> products = default(List<string>), int? updateWindowEnd = default(int?), int updateWindowStart = default(int))
        {
            this.Enabled = enabled;
            this.Interval = interval;
            this.Products = products;
            this.UpdateWindowEnd = updateWindowEnd;
            this.UpdateWindowStart = updateWindowStart;
        }

        /// <summary>
        /// Enable periodic Devolutions Agent self-update checks.
        /// </summary>
        /// <value>Enable periodic Devolutions Agent self-update checks.</value>
        [DataMember(Name = "Enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Minimum interval between auto-update checks, in seconds.  &#x60;0&#x60; means check once at &#x60;UpdateWindowStart&#x60; (default).
        /// </summary>
        /// <value>Minimum interval between auto-update checks, in seconds.  &#x60;0&#x60; means check once at &#x60;UpdateWindowStart&#x60; (default).</value>
        [DataMember(Name = "Interval", EmitDefaultValue = false)]
        public long Interval { get; set; }

        /// <summary>
        /// Products the agent autonomously polls for new versions (default: empty).
        /// </summary>
        /// <value>Products the agent autonomously polls for new versions (default: empty).</value>
        [DataMember(Name = "Products", EmitDefaultValue = false)]
        public List<string> Products { get; set; }

        /// <summary>
        /// End of the maintenance window as seconds past midnight in local time, exclusive.  &#x60;null&#x60; (default) means no upper bound - a single check fires at &#x60;UpdateWindowStart&#x60;. When end &lt; start the window crosses midnight.
        /// </summary>
        /// <value>End of the maintenance window as seconds past midnight in local time, exclusive.  &#x60;null&#x60; (default) means no upper bound - a single check fires at &#x60;UpdateWindowStart&#x60;. When end &lt; start the window crosses midnight.</value>
        [DataMember(Name = "UpdateWindowEnd", EmitDefaultValue = true)]
        public int? UpdateWindowEnd { get; set; }

        /// <summary>
        /// Start of the maintenance window as seconds past midnight in local time (default: &#x60;7200&#x60; &#x3D; 02:00).
        /// </summary>
        /// <value>Start of the maintenance window as seconds past midnight in local time (default: &#x60;7200&#x60; &#x3D; 02:00).</value>
        [DataMember(Name = "UpdateWindowStart", EmitDefaultValue = false)]
        public int UpdateWindowStart { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetUpdateScheduleRequest {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Interval: ").Append(Interval).Append("\n");
            sb.Append("  Products: ").Append(Products).Append("\n");
            sb.Append("  UpdateWindowEnd: ").Append(UpdateWindowEnd).Append("\n");
            sb.Append("  UpdateWindowStart: ").Append(UpdateWindowStart).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Interval (long) minimum
            if (this.Interval < (long)0)
            {
                yield return new ValidationResult("Invalid value for Interval, must be a value greater than or equal to 0.", new [] { "Interval" });
            }

            // UpdateWindowEnd (int?) minimum
            if (this.UpdateWindowEnd < (int?)0)
            {
                yield return new ValidationResult("Invalid value for UpdateWindowEnd, must be a value greater than or equal to 0.", new [] { "UpdateWindowEnd" });
            }

            // UpdateWindowStart (int) minimum
            if (this.UpdateWindowStart < (int)0)
            {
                yield return new ValidationResult("Invalid value for UpdateWindowStart, must be a value greater than or equal to 0.", new [] { "UpdateWindowStart" });
            }

            yield break;
        }
    }

}
