/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2026.2.4
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// A Task: the permanent record of one piece of work the provisioner asked Gateway to do  The work runs in the background; &#x60;state&#x60; and &#x60;payload&#x60; tell how it goes. The shape of &#x60;params&#x60; and &#x60;payload&#x60; belongs to the kind. For &#x60;recording.ai-analysis&#x60;, &#x60;payload&#x60; is an &#x60;AiAnalysisRunningPayload&#x60; while &#x60;running&#x60;, an &#x60;AiAnalysisSucceededPayload&#x60; once &#x60;succeeded&#x60;, and an &#x60;AiAnalysisFailedPayload&#x60; once &#x60;failed&#x60;.
    /// </summary>
    [DataContract(Name = "TaskInfo")]
    public partial class TaskInfo : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", IsRequired = true, EmitDefaultValue = true)]
        public TaskState State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TaskInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskInfo" /> class.
        /// </summary>
        /// <param name="attempts">Number of attempts started so far. (required).</param>
        /// <param name="createdAt">When the Task was created. (required).</param>
        /// <param name="deadlineAt">When an unfinished Task becomes failed, waiting and retries included. (required).</param>
        /// <param name="finishedAt">When it succeeded or failed..</param>
        /// <param name="id">Task ID, chosen by the provisioner. (required).</param>
        /// <param name="kind">Kind of work, such as &#x60;recording.ai-analysis&#x60;. (required).</param>
        /// <param name="varParams">What was asked, without secrets. (required).</param>
        /// <param name="payload">Details of the current state; null while &#x60;queued&#x60;..</param>
        /// <param name="startedAt">When its first attempt started..</param>
        /// <param name="state">state (required).</param>
        /// <param name="target">What the work is about, such as a session ID. (required).</param>
        public TaskInfo(int attempts = default(int), DateTime createdAt = default(DateTime), DateTime deadlineAt = default(DateTime), DateTime? finishedAt = default(DateTime?), Guid id = default(Guid), string kind = default(string), Object varParams = default(Object), Object payload = default(Object), DateTime? startedAt = default(DateTime?), TaskState state = default(TaskState), string target = default(string))
        {
            this.Attempts = attempts;
            this.CreatedAt = createdAt;
            this.DeadlineAt = deadlineAt;
            this.Id = id;
            // to ensure "kind" is required (not null)
            if (kind == null)
            {
                throw new ArgumentNullException("kind is a required property for TaskInfo and cannot be null");
            }
            this.Kind = kind;
            // to ensure "varParams" is required (not null)
            if (varParams == null)
            {
                throw new ArgumentNullException("varParams is a required property for TaskInfo and cannot be null");
            }
            this.Params = varParams;
            this.State = state;
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for TaskInfo and cannot be null");
            }
            this.Target = target;
            this.FinishedAt = finishedAt;
            this.Payload = payload;
            this.StartedAt = startedAt;
        }

        /// <summary>
        /// Number of attempts started so far.
        /// </summary>
        /// <value>Number of attempts started so far.</value>
        [DataMember(Name = "attempts", IsRequired = true, EmitDefaultValue = true)]
        public int Attempts { get; set; }

        /// <summary>
        /// When the Task was created.
        /// </summary>
        /// <value>When the Task was created.</value>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// When an unfinished Task becomes failed, waiting and retries included.
        /// </summary>
        /// <value>When an unfinished Task becomes failed, waiting and retries included.</value>
        [DataMember(Name = "deadlineAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime DeadlineAt { get; set; }

        /// <summary>
        /// When it succeeded or failed.
        /// </summary>
        /// <value>When it succeeded or failed.</value>
        [DataMember(Name = "finishedAt", EmitDefaultValue = true)]
        public DateTime? FinishedAt { get; set; }

        /// <summary>
        /// Task ID, chosen by the provisioner.
        /// </summary>
        /// <value>Task ID, chosen by the provisioner.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Kind of work, such as &#x60;recording.ai-analysis&#x60;.
        /// </summary>
        /// <value>Kind of work, such as &#x60;recording.ai-analysis&#x60;.</value>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public string Kind { get; set; }

        /// <summary>
        /// What was asked, without secrets.
        /// </summary>
        /// <value>What was asked, without secrets.</value>
        [DataMember(Name = "params", IsRequired = true, EmitDefaultValue = true)]
        public Object Params { get; set; }

        /// <summary>
        /// Details of the current state; null while &#x60;queued&#x60;.
        /// </summary>
        /// <value>Details of the current state; null while &#x60;queued&#x60;.</value>
        [DataMember(Name = "payload", EmitDefaultValue = true)]
        public Object Payload { get; set; }

        /// <summary>
        /// When its first attempt started.
        /// </summary>
        /// <value>When its first attempt started.</value>
        [DataMember(Name = "startedAt", EmitDefaultValue = true)]
        public DateTime? StartedAt { get; set; }

        /// <summary>
        /// What the work is about, such as a session ID.
        /// </summary>
        /// <value>What the work is about, such as a session ID.</value>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskInfo {\n");
            sb.Append("  Attempts: ").Append(Attempts).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  DeadlineAt: ").Append(DeadlineAt).Append("\n");
            sb.Append("  FinishedAt: ").Append(FinishedAt).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Params: ").Append(Params).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Attempts (int) minimum
            if (this.Attempts < (int)0)
            {
                yield return new ValidationResult("Invalid value for Attempts, must be a value greater than or equal to 0.", new [] { "Attempts" });
            }

            yield break;
        }
    }

}
