/*
 * devolutions-gateway
 *
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2026.2.4
 * Contact: infos@devolutions.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Gateway.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Gateway.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Gateway.Client.Model
{
    /// <summary>
    /// A background task and its status.  &#x60;substate&#x60; is set only when &#x60;state&#x60; is &#x60;running&#x60;, &#x60;result&#x60; only when it is &#x60;success&#x60;, and &#x60;error&#x60; only when it is &#x60;failed&#x60;. Both &#x60;substate&#x60; and &#x60;result&#x60; are kind-specific: for &#x60;ai-log&#x60;, &#x60;substate&#x60; is an &#x60;AiLogSubstate&#x60;.
    /// </summary>
    [DataContract(Name = "TaskInfo")]
    public partial class TaskInfo : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", IsRequired = true, EmitDefaultValue = true)]
        public TaskState State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TaskInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskInfo" /> class.
        /// </summary>
        /// <param name="error">Why the task failed..</param>
        /// <param name="id">Task ID. (required).</param>
        /// <param name="kind">Task kind, as in the &#x60;jet_tk&#x60; claim of the TASK token. (required).</param>
        /// <param name="result">Result of a successful task..</param>
        /// <param name="state">state (required).</param>
        /// <param name="substate">Progress of a running task..</param>
        public TaskInfo(string error = default(string), Guid id = default(Guid), string kind = default(string), Object result = default(Object), TaskState state = default(TaskState), Object substate = default(Object))
        {
            this.Id = id;
            // to ensure "kind" is required (not null)
            if (kind == null)
            {
                throw new ArgumentNullException("kind is a required property for TaskInfo and cannot be null");
            }
            this.Kind = kind;
            this.State = state;
            this.Error = error;
            this.Result = result;
            this.Substate = substate;
        }

        /// <summary>
        /// Why the task failed.
        /// </summary>
        /// <value>Why the task failed.</value>
        [DataMember(Name = "error", EmitDefaultValue = true)]
        public string Error { get; set; }

        /// <summary>
        /// Task ID.
        /// </summary>
        /// <value>Task ID.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Task kind, as in the &#x60;jet_tk&#x60; claim of the TASK token.
        /// </summary>
        /// <value>Task kind, as in the &#x60;jet_tk&#x60; claim of the TASK token.</value>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public string Kind { get; set; }

        /// <summary>
        /// Result of a successful task.
        /// </summary>
        /// <value>Result of a successful task.</value>
        [DataMember(Name = "result", EmitDefaultValue = true)]
        public Object Result { get; set; }

        /// <summary>
        /// Progress of a running task.
        /// </summary>
        /// <value>Progress of a running task.</value>
        [DataMember(Name = "substate", EmitDefaultValue = true)]
        public Object Substate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskInfo {\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Substate: ").Append(Substate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
