/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AckRequest { 
    /**
     * Array of event IDs to acknowledge (1-10000 items, ULID format)
     */
    ids: Array<string>;
}

