/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payload of a `failed` AI analysis Task: why it failed
 */
export interface AiAnalysisFailedPayload { 
    /**
     * Number of attempts started.
     */
    attempts: number;
    /**
     * What went wrong: a text, except for `timed out`, where it is `{ \"lastPayload\": <payload before the timeout> }`.
     */
    details: any | null;
    /**
     * Kind of failure, such as `permanent error`, `attempts exhausted`, `key lost` or `timed out`.
     */
    reason: string;
}

