/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payload of a `running` AI analysis Task: its progress
 */
export interface AiAnalysisRunningPayload { 
    /**
     * Work done in the step: bytes read while `reading`, parts described while `describing`.
     */
    done?: number | null;
    /**
     * Short sentence for people following the analysis, such as `asking the AI: 2 of 5 chunks described`.
     */
    message?: string | null;
    /**
     * Part of the step done, from 0 to 100.
     */
    percent?: number | null;
    /**
     * Current step: `preparing` (the attempt starts), `reading` (the recordings are read), `describing` (the AI is asked about the recording, part by part), then `writing` (the log is written).
     */
    step: string;
    /**
     * Work the step has in all, in the same unit as `done`.
     */
    total?: number | null;
}

