/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Transcript chunks sent to the AI provider so far, out of `total`.
 */
export interface AiLogSubstateOneOf1 { 
    done: number;
    step: AiLogSubstateOneOf1.Step;
    total: number;
}
export namespace AiLogSubstateOneOf1 {
    export type Step = 'describing';
    export const Step = {
        Describing: 'describing' as Step
    };
}


