/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * AI provider to ask; `openai-compatible` needs a base URL
 */
export type AiProvider = 'openai' | 'anthropic' | 'mistral' | 'gemini' | 'openai-compatible';

export const AiProvider = {
    Openai: 'openai' as AiProvider,
    Anthropic: 'anthropic' as AiProvider,
    Mistral: 'mistral' as AiProvider,
    Gemini: 'gemini' as AiProvider,
    OpenaiCompatible: 'openai-compatible' as AiProvider
};

