/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const HostScanStateDto = {
    Queued: 'queued',
    Probing: 'probing',
    Reachable: 'reachable',
    Unreachable: 'unreachable'
} as const;
export type HostScanStateDto = typeof HostScanStateDto[keyof typeof HostScanStateDto];

