/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Identity { 
    /**
     * This Gateway\'s hostname
     */
    hostname: string;
    /**
     * This Gateway\'s unique ID
     */
    id?: string | null;
    /**
     * Gateway service version
     */
    version?: string | null;
}

