/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressFamily } from './addressFamily';


export interface InterfaceInfo { 
    address: string;
    broadcast?: string | null;
    family: AddressFamily;
    mac?: string | null;
    netmask?: string | null;
}
export namespace InterfaceInfo {
}


