/**
 * devolutions-gateway
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2022.3.0
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JrlInfo { 
    /**
     * JWT \"Issued At\" claim of JRL
     */
    iat: number;
    /**
     * Unique ID for current JRL
     */
    jti: string;
}

