/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NetworkInterfaceDto } from './networkInterfaceDto';
import { NetworkScanSourceCapabilitiesDto } from './networkScanSourceCapabilitiesDto';


export interface NetworkScanSourceDto { 
    address: string;
    broadcastAddress?: string | null;
    capabilities: NetworkScanSourceCapabilitiesDto;
    endAddress: string;
    'interface': NetworkInterfaceDto;
    prefixLength?: number | null;
    startAddress: string;
}

