/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type NetworkScanResultKindDto = 'host' | 'service';

export const NetworkScanResultKindDto = {
    Host: 'host' as NetworkScanResultKindDto,
    Service: 'service' as NetworkScanResultKindDto
};

