/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PreflightOperationKind = 'get-version' | 'get-agent-version' | 'get-running-session-count' | 'get-recording-storage-health' | 'push-token' | 'push-credentials' | 'lookup-host';

export const PreflightOperationKind = {
    GetVersion: 'get-version' as PreflightOperationKind,
    GetAgentVersion: 'get-agent-version' as PreflightOperationKind,
    GetRunningSessionCount: 'get-running-session-count' as PreflightOperationKind,
    GetRecordingStorageHealth: 'get-recording-storage-health' as PreflightOperationKind,
    PushToken: 'push-token' as PreflightOperationKind,
    PushCredentials: 'push-credentials' as PreflightOperationKind,
    LookupHost: 'lookup-host' as PreflightOperationKind
};

