/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetConnectionOptions } from './targetConnectionOptions';
import { AppCredential } from './appCredential';
import { PreflightOperationKind } from './preflightOperationKind';


export interface PreflightOperation { 
    connection_options?: TargetConnectionOptions | null;
    /**
     * The hostname to perform DNS resolution on.  Required for \"resolve-host\" kind.
     */
    host_to_resolve?: string | null;
    /**
     * Unique ID identifying the preflight operation.
     */
    id: string;
    kind: PreflightOperationKind;
    proxy_credential?: AppCredential | null;
    target_credential?: AppCredential | null;
    /**
     * Retention duration in seconds for data provisioned by this operation.  For \"provision-credentials\", this is the maximum staging time before the first credential checkout. After checkout, Gateway retains the credentials for later connections authorized for the same association.  Optional parameter for \"provision-token\", \"provision-credentials\", and \"provision-connection-options\" kinds.
     */
    time_to_live?: number | null;
    /**
     * The token to be stored on the proxy-side.  Required for \"provision-token\", \"provision-credentials\", and \"provision-connection-options\" kinds.
     */
    token?: string | null;
}
export namespace PreflightOperation {
}


