/**
 * devolutions-gateway
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2024.3.2
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PubKeyFormat = 'Spki' | 'Pkcs1';

export const PubKeyFormat = {
    Spki: 'Spki' as PubKeyFormat,
    Pkcs1: 'Pkcs1' as PubKeyFormat
};

