/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Session Recording Log search request
 */
export interface RecordingLogSearchRequest { 
    /**
     * Match case exactly instead of ignoring case
     */
    caseSensitive?: boolean;
    /**
     * When not empty, only entries whose `event` is one of these values are considered
     */
    eventTypes?: Array<string>;
    /**
     * Only entries whose `timestamp` is at or after this instant are considered
     */
    from?: string | null;
    /**
     * Maximum number of hits to return (default 100, capped at 1000)
     */
    limit?: number | null;
    /**
     * Text to look for; an empty query matches every entry
     */
    query?: string;
    /**
     * Recordings to search, in the order results are returned  When omitted, recordings stored on this instance are searched newest first, up to the 10,000 most recently modified ones. An empty list searches nothing.
     */
    recordingIds?: Array<string> | null;
    /**
     * Only entries whose `timestamp` is before this instant are considered
     */
    to?: string | null;
}

