/**
 * devolutions-gateway
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2022.2.2
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConnectionMode } from './connectionMode';


export interface SessionInfo { 
    application_protocol: string;
    association_id: string;
    connection_mode: ConnectionMode;
    destination_host?: string;
    filtering_policy: boolean;
    recording_policy: boolean;
    start_timestamp: string;
}

