/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskState } from './taskState';


/**
 * A Task: the permanent record of one piece of work the provisioner asked Gateway to do  The work runs in the background; `state` and `payload` tell how it goes. The shape of `params` and `payload` belongs to the kind. For `recording.ai-analysis`, `payload` is an `AiAnalysisRunningPayload` while `running`, an `AiAnalysisSucceededPayload` once `succeeded`, and an `AiAnalysisFailedPayload` once `failed`.
 */
export interface TaskInfo { 
    /**
     * Number of attempts started so far.
     */
    attempts: number;
    /**
     * When the Task was created.
     */
    createdAt: string;
    /**
     * When an unfinished Task becomes failed, waiting and retries included.
     */
    deadlineAt: string;
    /**
     * When it succeeded or failed.
     */
    finishedAt?: string | null;
    /**
     * Task ID, chosen by the provisioner.
     */
    id: string;
    /**
     * Kind of work, such as `recording.ai-analysis`.
     */
    kind: string;
    /**
     * What was asked, without secrets.
     */
    params: object;
    /**
     * Details of the current state; null while `queued`.
     */
    payload?: object | null;
    /**
     * When its first attempt started.
     */
    startedAt?: string | null;
    state: TaskState;
    /**
     * What the work is about, such as a session ID.
     */
    target: string;
}
export namespace TaskInfo {
}


