/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskState } from './taskState';


/**
 * A background task and its status.  `substate` is set only when `state` is `running`, `result` only when it is `success`, and `error` only when it is `failed`. Both `substate` and `result` are kind-specific: for `recording.ai-analysis`, `substate` is an `RecordingAiAnalysisSubstate`.
 */
export interface TaskInfo { 
    /**
     * Why the task failed.
     */
    error?: string | null;
    /**
     * Task ID.
     */
    id: string;
    /**
     * Task kind, as in `jet_task.kind` in the TASK token.
     */
    kind: string;
    /**
     * Result of a successful task.
     */
    result?: object | null;
    state: TaskState;
    /**
     * Progress of a running task.
     */
    substate?: object | null;
}
export namespace TaskInfo {
}


