/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Stable code telling a client why a task request failed; safe to show.
 */
export type TaskErrorCode = 'invalid_params' | 'missing_model' | 'missing_api_key' | 'missing_base_url' | 'invalid_ai_settings' | 'recording_active' | 'task_not_found' | 'internal';

export const TaskErrorCode = {
    InvalidParams: 'invalid_params' as TaskErrorCode,
    MissingModel: 'missing_model' as TaskErrorCode,
    MissingApiKey: 'missing_api_key' as TaskErrorCode,
    MissingBaseUrl: 'missing_base_url' as TaskErrorCode,
    InvalidAiSettings: 'invalid_ai_settings' as TaskErrorCode,
    RecordingActive: 'recording_active' as TaskErrorCode,
    TaskNotFound: 'task_not_found' as TaskErrorCode,
    Internal: 'internal' as TaskErrorCode
};

