/**
 * devolutions-gateway
 *
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Why a task was not started.
 */
export interface TaskErrorResponse { 
    /**
     * Stable error code, such as `invalid_params`, `missing_model`, `missing_api_key`, `missing_base_url`, `invalid_ai_settings` or `recording_active`.
     */
    error: string;
}

