[package]
name = "mcp-proxy"
version = "0.0.0"
edition = "2024"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
description = "Cross-platform MCP (Model Context Protocol) proxy tool"
readme = "README.md"
keywords = ["mcp", "proxy", "cli", "llm", "json-rpc"]
categories = ["command-line-utilities", "network-programming"]
publish = false

[lib]
doctest = false
test = false

[dependencies]
tokio = { version = "1", features = ["rt", "macros", "io-util", "process", "fs", "net"] }
ureq = "2"
tinyjson = "2"
anyhow = "1"
tracing = "0.1"
