/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Pedm.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Pedm.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Pedm.Client.Model
{
    /// <summary>
    /// Defines ElevationMethod
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ElevationMethod
    {
        /// <summary>
        /// Enum LocalAdmin for value: LocalAdmin
        /// </summary>
        [EnumMember(Value = "LocalAdmin")]
        LocalAdmin = 1,

        /// <summary>
        /// Enum VirtualAccount for value: VirtualAccount
        /// </summary>
        [EnumMember(Value = "VirtualAccount")]
        VirtualAccount = 2
    }

    public static class ElevationMethodExtensions
    {
        /// <summary>
        /// Returns the value as string for a given variant
        /// </summary>
        public static string ToValue(this ElevationMethod variant)
        {
            switch (variant)
            {
                case ElevationMethod.LocalAdmin:
                    return "LocalAdmin";
                case ElevationMethod.VirtualAccount:
                    return "VirtualAccount";
                default:
                    throw new ArgumentOutOfRangeException(nameof(variant), $"Unexpected variant: {variant}");
            }
        }
    }

}
