/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Pedm.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Pedm.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Pedm.Client.Model
{
    /// <summary>
    /// GetProfilesMeResponse
    /// </summary>
    [DataContract(Name = "GetProfilesMeResponse")]
    public partial class GetProfilesMeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetProfilesMeResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetProfilesMeResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetProfilesMeResponse" /> class.
        /// </summary>
        /// <param name="active">active.</param>
        /// <param name="available">available (required).</param>
        public GetProfilesMeResponse(Guid active = default(Guid), List<Guid> available = default(List<Guid>))
        {
            // to ensure "available" is required (not null)
            if (available == null)
            {
                throw new ArgumentNullException("available is a required property for GetProfilesMeResponse and cannot be null");
            }
            this.Available = available;
            this.Active = active;
        }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name = "Active", EmitDefaultValue = false)]
        public Guid Active { get; set; }

        /// <summary>
        /// Gets or Sets Available
        /// </summary>
        [DataMember(Name = "Available", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> Available { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetProfilesMeResponse {\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Available: ").Append(Available).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
