/*
 * Devolutions PEDM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Devolutions.Pedm.Client.Client.FileParameter;
using OpenAPIDateConverter = Devolutions.Pedm.Client.Client.OpenAPIDateConverter;

namespace Devolutions.Pedm.Client.Model
{
    /// <summary>
    /// SignatureFilter
    /// </summary>
    [DataContract(Name = "SignatureFilter")]
    public partial class SignatureFilter : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignatureFilter" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignatureFilter() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignatureFilter" /> class.
        /// </summary>
        /// <param name="checkAuthenticode">checkAuthenticode (required).</param>
        public SignatureFilter(bool checkAuthenticode = default(bool))
        {
            this.CheckAuthenticode = checkAuthenticode;
        }

        /// <summary>
        /// Gets or Sets CheckAuthenticode
        /// </summary>
        [DataMember(Name = "CheckAuthenticode", IsRequired = true, EmitDefaultValue = true)]
        public bool CheckAuthenticode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignatureFilter {\n");
            sb.Append("  CheckAuthenticode: ").Append(CheckAuthenticode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
