openapi: 3.1.0
info:
  title: Devolutions PEDM API
  version: ''
paths:
  /about:
    get:
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AboutData'
  /elevate/temporary:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElevateTemporaryPayload'
        required: true
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: no content
  /elevate/session:
    post:
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: no content
  /launch:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchPayload'
        required: true
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchResponse'
  /revoke:
    post:
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: no content
  /status:
    get:
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /log/jit:
    get:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JitElevationLogQueryOptions'
        required: true
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JitElevationLogPage'
  /log/jit/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
        style: simple
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JitElevationLogRow'
  /policy/me:
    get:
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: |-
            Returns some information about the current user and active profiles.

            If there is no active profile, the `active` UUID will be full of zeroes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProfilesMeResponse'
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OptionalId'
        required: true
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: no content
  /policy/profiles:
    get:
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: no content
  /policy/profiles/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          format: uuid
        style: simple
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          format: uuid
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: no content
    delete:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          format: uuid
        style: simple
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: no content
  /policy/assignments:
    get:
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Assignment'
  /policy/assignments/{id}:
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          format: uuid
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: no content
  /policy/users:
    get:
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    AboutData:
      type: object
      required:
      - CurrentRequestCount
      - RunId
      - StartTime
      - StartupRequestCount
      properties:
        CurrentRequestCount:
          type: integer
          format: int32
        LastRequestTime:
          description: |-
            The time of the most recent request.

            This can be `None` if `/about` is the first request made.
          type: string
          format: date-time
          nullable: true
        RunId:
          type: integer
          format: int32
        StartTime:
          type: string
          format: date-time
        StartupRequestCount:
          type: integer
          format: int32
    Assignment:
      type: object
      required:
      - Profile
      - Users
      properties:
        Profile:
          $ref: '#/components/schemas/Profile'
        Users:
          type: array
          items:
            $ref: '#/components/schemas/User'
    AuthenticodeSignatureStatus:
      type: string
      enum:
      - Valid
      - Incompatible
      - NotSigned
      - HashMismatch
      - NotSupportedFileFormat
      - NotTrusted
    Certificate:
      type: object
      required:
      - Base64
      - Eku
      - Issuer
      - SerialNumber
      - Subject
      - Thumbprint
      properties:
        Base64:
          type: string
        Eku:
          type: array
          items:
            type: string
        Issuer:
          type: string
        SerialNumber:
          type: string
        Subject:
          type: string
        Thumbprint:
          $ref: '#/components/schemas/Hash'
    ElevateTemporaryPayload:
      type: object
      required:
      - Seconds
      properties:
        Seconds:
          description: |-
            The number of seconds to elevate the user for.

            This must be between 1 and `i32::MAX`.
          type: integer
          format: int64
          minimum: 0.0
    ElevationConfigurations:
      type: object
      required:
      - Session
      - Temporary
      properties:
        Session:
          $ref: '#/components/schemas/SessionElevationConfiguration'
        Temporary:
          $ref: '#/components/schemas/TemporaryElevationConfiguration'
    ElevationKind:
      type: string
      enum:
      - AutoApprove
      - Confirm
      - ReasonApproval
      - Deny
    ElevationMethod:
      type: string
      enum:
      - LocalAdmin
      - VirtualAccount
    Error:
      description: The original crate-wide error type.
      type: string
      enum:
      - AccessDenied
      - NotFound
      - InvalidParameter
      - Internal
      - Cancelled
    ErrorResponse:
      type: object
      required:
      - Kind
      - Win32Error
      properties:
        Kind:
          $ref: '#/components/schemas/Error'
        Win32Error:
          type: integer
          format: int32
          minimum: 0.0
    GetProfilesMeResponse:
      description: |-
        Returns some information about the current user and active profiles.

        If there is no active profile, the `active` UUID will be full of zeroes.
      type: object
      required:
      - Active
      - Available
      properties:
        Active:
          type: string
          format: uuid
        Available:
          type: array
          items:
            type: string
            format: uuid
    Hash:
      type: object
      required:
      - Sha1
      - Sha256
      properties:
        Sha1:
          type: string
        Sha256:
          type: string
    JitElevationLogPage:
      type: object
      required:
      - Results
      - TotalPages
      - TotalRecords
      properties:
        Results:
          type: array
          items:
            $ref: '#/components/schemas/JitElevationLogRow'
        TotalPages:
          type: integer
          format: int32
          minimum: 0.0
        TotalRecords:
          type: integer
          format: int32
          minimum: 0.0
    JitElevationLogQueryOptions:
      type: object
      required:
      - EndTime
      - PageNumber
      - PageSize
      - SortColumn
      - SortDescending
      - StartTime
      properties:
        EndTime:
          type: integer
          format: int64
        PageNumber:
          type: integer
          format: int32
          minimum: 0.0
        PageSize:
          type: integer
          format: int32
          minimum: 0.0
        SortColumn:
          type: string
        SortDescending:
          type: boolean
        StartTime:
          type: integer
          format: int64
        User:
          $ref: '#/components/schemas/User'
          nullable: true
    JitElevationLogRow:
      type: object
      required:
      - Id
      - Success
      - Timestamp
      properties:
        AskerPath:
          type: string
          nullable: true
        Id:
          type: integer
          format: int64
        Success:
          type: integer
          format: int64
        TargetCommandLine:
          type: string
          nullable: true
        TargetHash:
          $ref: '#/components/schemas/Hash'
          nullable: true
        TargetPath:
          type: string
          nullable: true
        TargetSignature:
          $ref: '#/components/schemas/Signature'
          nullable: true
        TargetWorkingDirectory:
          type: string
          nullable: true
        Timestamp:
          type: integer
          format: int64
        User:
          $ref: '#/components/schemas/User'
          nullable: true
    LaunchPayload:
      type: object
      required:
      - CreationFlags
      properties:
        CommandLine:
          type: string
          nullable: true
        CreationFlags:
          type: integer
          format: int32
          minimum: 0.0
        ExecutablePath:
          type: string
          nullable: true
        StartupInfo:
          $ref: '#/components/schemas/StartupInfoDto'
          nullable: true
        WorkingDirectory:
          type: string
          nullable: true
    LaunchResponse:
      type: object
      required:
      - ProcessId
      - ThreadId
      properties:
        ProcessId:
          type: integer
          format: int32
          minimum: 0.0
        ThreadId:
          type: integer
          format: int32
          minimum: 0.0
    OptionalId:
      type: object
      properties:
        Id:
          type: string
          format: uuid
          nullable: true
    PathIdParameter:
      type: object
      required:
      - id
      properties:
        id:
          type: string
          format: uuid
    PathIntIdPath:
      type: object
      required:
      - id
      properties:
        id:
          type: integer
          format: int64
    Profile:
      type: object
      required:
      - DefaultElevationKind
      - ElevationMethod
      - ElevationSettings
      - Id
      - Name
      - PromptSecureDesktop
      properties:
        DefaultElevationKind:
          $ref: '#/components/schemas/ElevationKind'
        ElevationMethod:
          $ref: '#/components/schemas/ElevationMethod'
        ElevationSettings:
          $ref: '#/components/schemas/ElevationConfigurations'
        Id:
          type: string
          format: uuid
        Name:
          type: string
        PromptSecureDesktop:
          type: boolean
    SessionElevationConfiguration:
      type: object
      required:
      - Enabled
      properties:
        Enabled:
          type: boolean
    SessionElevationStatus:
      type: object
      required:
      - Enabled
      properties:
        Enabled:
          type: boolean
    Signature:
      type: object
      required:
      - Status
      properties:
        Certificates:
          type: array
          items:
            $ref: '#/components/schemas/Certificate'
          nullable: true
        Signer:
          $ref: '#/components/schemas/Signer'
          nullable: true
        Status:
          $ref: '#/components/schemas/AuthenticodeSignatureStatus'
    Signer:
      type: object
      required:
      - Issuer
      properties:
        Issuer:
          type: string
    StartupInfoDto:
      type: object
      required:
      - FillAttribute
      - Flags
      - ShowWindow
      - X
      - XCountChars
      - XSize
      - Y
      - YCountChars
      - YSize
      properties:
        Desktop:
          type: string
          nullable: true
        FillAttribute:
          type: integer
          format: int32
          minimum: 0.0
        Flags:
          type: integer
          format: int32
          minimum: 0.0
        ParentPid:
          type: integer
          format: int32
          minimum: 0.0
          nullable: true
        ShowWindow:
          type: integer
          format: int32
          minimum: 0.0
        Title:
          type: string
          nullable: true
        X:
          type: integer
          format: int32
          minimum: 0.0
        XCountChars:
          type: integer
          format: int32
          minimum: 0.0
        XSize:
          type: integer
          format: int32
          minimum: 0.0
        Y:
          type: integer
          format: int32
          minimum: 0.0
        YCountChars:
          type: integer
          format: int32
          minimum: 0.0
        YSize:
          type: integer
          format: int32
          minimum: 0.0
    StatusResponse:
      type: object
      required:
      - Elevated
      - Session
      - Temporary
      properties:
        Elevated:
          type: boolean
        Session:
          $ref: '#/components/schemas/SessionElevationStatus'
        Temporary:
          $ref: '#/components/schemas/TemporaryElevationStatus'
    TemporaryElevationConfiguration:
      type: object
      required:
      - Enabled
      - MaximumSeconds
      properties:
        Enabled:
          type: boolean
        MaximumSeconds:
          type: integer
          format: int64
          minimum: 0.0
    TemporaryElevationStatus:
      type: object
      required:
      - Enabled
      - MaximumSeconds
      - TimeLeft
      properties:
        Enabled:
          type: boolean
        MaximumSeconds:
          type: integer
          format: int64
          minimum: 0.0
        TimeLeft:
          type: integer
          format: int64
          minimum: 0.0
    User:
      type: object
      required:
      - AccountName
      - AccountSid
      - DomainName
      - DomainSid
      properties:
        AccountName:
          type: string
        AccountSid:
          type: string
        DomainName:
          type: string
        DomainSid:
          type: string

