[package]
name = "proxy-generators"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2021"
publish = false

[dependencies]
proxy-types = { path = "../proxy-types" }
proptest = "1.2.0"
