packages:
  - 'packages/*'
  - 'apps/*'
  - 'tools/*'
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@devolutions/*'
