[package]
name = "picky-krb"
version = "0.0.0"
authors = ["Devolutions Inc."]
edition = "2021"
publish = false

[dependencies]
picky-asn1 = "0.5.0"
picky-asn1-der = { path = "../../../picky-rs/picky-asn1-der", version = "0.3.0" }
serde = { version = "1.0.136", features = ["derive"] }
byteorder = "1.1.0"
thiserror = "1.0.30"
