[package]
name = "picky-krb"
version = "0.0.0"
authors = ["Devolutions Inc."]
edition = "2021"
publish = false

[dependencies]
picky-asn1 = "0.5"
picky-asn1-der = "0.3"
serde = { version = "1.0.130", features = ["derive"] }
