/* tslint:disable */
/* eslint-disable */
/**
 * devolutions-gateway
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2022.2.2
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClockDiagnostic
 */
export interface ClockDiagnostic {
    /**
     * 
     * @type {number}
     * @memberof ClockDiagnostic
     */
    timestampMillis: number;
    /**
     * 
     * @type {number}
     * @memberof ClockDiagnostic
     */
    timestampSecs: number;
}

/**
 * Check if a given object implements the ClockDiagnostic interface.
 */
export function instanceOfClockDiagnostic(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "timestampMillis" in value;
    isInstance = isInstance && "timestampSecs" in value;

    return isInstance;
}

export function ClockDiagnosticFromJSON(json: any): ClockDiagnostic {
    return ClockDiagnosticFromJSONTyped(json, false);
}

export function ClockDiagnosticFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClockDiagnostic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestampMillis': json['timestamp_millis'],
        'timestampSecs': json['timestamp_secs'],
    };
}

export function ClockDiagnosticToJSON(value?: ClockDiagnostic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp_millis': value.timestampMillis,
        'timestamp_secs': value.timestampSecs,
    };
}

