/* tslint:disable */
/* eslint-disable */
/**
 * devolutions-gateway
 * Protocol-aware fine-grained relay server
 *
 * The version of the OpenAPI document: 2022.2.2
 * Contact: infos@devolutions.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DataEncoding = {
    Multibase: 'Multibase',
    Base64: 'Base64',
    Base64Pad: 'Base64Pad',
    Base64Url: 'Base64Url',
    Base64UrlPad: 'Base64UrlPad'
} as const;
export type DataEncoding = typeof DataEncoding[keyof typeof DataEncoding];


export function DataEncodingFromJSON(json: any): DataEncoding {
    return DataEncodingFromJSONTyped(json, false);
}

export function DataEncodingFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataEncoding {
    return json as DataEncoding;
}

export function DataEncodingToJSON(value?: DataEncoding | null): any {
    return value as any;
}

