[package]
name = "jmux-generators"
version = "0.0.0"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
edition = "2024"
publish = false

[dependencies]
jmux-proto = { path = "../jmux-proto" }
proptest = "1.7"
