name: Create new release

on:
  push:
  workflow_dispatch:
    dry-run:
      description: 'If true, the workflow only indicates which artifacts would be uploaded'
      required: true
      type: boolean
      default: 'true'

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  call-package-workflow:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    needs: [ call-ci-workflow ]
    with:
      run: ${{ github.run_id }}

  call-release-workflow:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    needs: [ call-package-workflow ]
    with:
      run: ${{ github.run_id }}
