name: Create New Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The commit SHA to build
        required: false
        type: string
      dry-run:
          description: If true, the workflow only indicates which artifacts would be uploaded
          required: true
          type: boolean
          default: true

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      ref: ${{ inputs.ref }}

  call-package-workflow:
    needs: [call-ci-workflow]
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      ref: ${{ inputs.ref }}

  call-release-workflow:
    if: ${{ github.ref == 'refs/heads/master' || inputs.dry-run == true }}
    needs: [call-package-workflow]
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run }}
