name: Create New Release

on:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: "The commit SHA to build"
        required: false
        type: string

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      ref: ${{ github.event.inputs.ref }}

  call-package-workflow:
    uses: ./.github/workflows/package.yml
    secrets: inherit
    needs: [ call-ci-workflow ]

  call-release-workflow:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    needs: [ call-package-workflow ]
