export * from './config.service';
import { ConfigService } from './config.service';
export * from './diagnostics.service';
import { DiagnosticsService } from './diagnostics.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './heartbeat.service';
import { HeartbeatService } from './heartbeat.service';
export * from './jrec.service';
import { JrecService } from './jrec.service';
export * from './jrl.service';
import { JrlService } from './jrl.service';
export * from './sessions.service';
import { SessionsService } from './sessions.service';
export * from './update.service';
import { UpdateService } from './update.service';
export * from './webApp.service';
import { WebAppService } from './webApp.service';
export const APIS = [ConfigService, DiagnosticsService, HealthService, HeartbeatService, JrecService, JrlService, SessionsService, UpdateService, WebAppService];
